name: crongui
base: core22
version: '0.1'
summary: A simple GUI crontab editor
description: |
  CronGUI is a simple graphical user interface for managing crontab entries.
  It allows users to easily add, edit, and delete cron jobs without the need
  to remember the crontab syntax or use command-line tools.

grade: devel
confinement: strict

apps:
  crongui:
    command: bin/python3 $SNAP/bin/crongui.py
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - network
      - mount-observe
      - process-control
      - system-observe

parts:
  crongui:
    plugin: python
    source: .
    stage-packages:
      - python3-tk
      - python3-pip
      - cron
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp $CRAFT_PART_SRC/crongui.py $CRAFT_PART_INSTALL/bin/
